version: '3.5'
services:
  dev:
    container_name: annococo
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '16gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
    working_dir: /workspace
    tty: true
