name: Create Release Note

on:
  push:
    branches: [ main ]

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

      # 前回のりリースタグを取得する
    - name: Get previous tag
      id: pre_tag
      run: |
        echo "::set-output name=pre_tag::$(curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)"

    # PRのタイトルからリリースタグを作成する
    - name: Create Release Tag And Note
      env:
        # このトークンは自動生成されるのでsecretsを登録する必要ない
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # PRのタイトルと内容をRelease内容に追加する
        RELEASE_TAG: ${{ github.event.pull_request.title }}
      uses: release-drafter/release-drafter@v5
      with:
        tag: ${{ env.RELEASE_TAG }}
        name: Release ${{ env.RELEASE_TAG }}
        version: ${{ env.RELEASE_TAG }}
        publish: true
